INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');

INSERT INTO USER_DATA (ID, VERSION, FIRSTNAME, LASTNAME, EMAIL) VALUES (1, 0, 'adminaa', 'admina', 'admin@gmail.com');
INSERT INTO USER_DATA (ID, VERSION, FIRSTNAME, LASTNAME, EMAIL) VALUES (2, 0, 'akos', 'negrut', 'negrut@gmail.com');
INSERT INTO USER_DATA (ID, VERSION, FIRSTNAME, LASTNAME, EMAIL) VALUES (3, 0, 'gergely', 'jakab', 'jakab@gmail.com');
INSERT INTO USER_DATA (ID, VERSION, FIRSTNAME, LASTNAME, EMAIL) VALUES (4, 0, 'ferenc', 'szilagyi', 'szilagyi@gmail.com');
INSERT INTO USER_DATA (ID, VERSION, FIRSTNAME, LASTNAME, EMAIL) VALUES (5, 0, 'lajos', 'kosa', 'kosa@gmail.com');
INSERT INTO USER_DATA (ID, VERSION, FIRSTNAME, LASTNAME, EMAIL) VALUES (6, 0, 'erika', 'javor', 'javor@gmail.com');

INSERT INTO USER_LOGIN (ID, VERSION, USERNAME, PASSWORD, ROLE) VALUES (1, 0, 'admin', 'admin', 'ADMIN');
INSERT INTO USER_LOGIN (ID, VERSION, USERNAME, PASSWORD, ROLE) VALUES (2, 0, 'negrut', 'gyere', 'USER');
INSERT INTO USER_LOGIN (ID, VERSION, USERNAME, PASSWORD, ROLE) VALUES (3, 0, 'jakab', 'menjel', 'USER');
INSERT INTO USER_LOGIN (ID, VERSION, USERNAME, PASSWORD, ROLE) VALUES (4, 0, 'szilagyi', 'ferenc', 'USER');
INSERT INTO USER_LOGIN (ID, VERSION, USERNAME, PASSWORD, ROLE) VALUES (5, 0, 'kosa', 'kosa', 'USER');
INSERT INTO USER_LOGIN (ID, VERSION, USERNAME, PASSWORD, ROLE) VALUES (6, 0, 'javor', 'javor', 'USER');

INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (1, 0, 'Vonatjegy', 1200, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (2, 0, 'Keztorlo', 600, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (3, 0, 'Kenyer', 200, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (4, 0, 'Langszoro', 12000, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (5, 0, 'Utlevel', 2400, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (6, 0, 'Gyogyszer', 2300, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (7, 0, 'Fenykepezogep', 22500, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (8, 0, 'Zsebkendo', 400, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (9, 0, 'Kabat', 7400, 'www.google.hu', 'f');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (10, 0, 'Konyv', 900, 'www.google.hu', 't');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (11, 0, 'Lancfuresz', 8000, 'www.google.hu', 't');
INSERT INTO PRESENT (ID, VERSION, NAME, PRICE, LINK, HIDDEN) VALUES (12, 0, 'Kerekpar', 120000, 'www.google.hu', 't');

INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (1, 0, 'Eleg tre!', '2016-11-24');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (2, 0, 'Micsoda?', '2015-01-10');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (3, 0, 'Kicsoda?', '2014-02-24');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (4, 0, 'Vegyel egyet', '2013-10-02');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (5, 0, 'KappaPride', '2017-02-14');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (6, 0, 'Ez lopott!', '2012-05-11');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (7, 0, 'Hozd vissza!', '2007-10-01');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (8, 0, 'Kernek szepen egyet...', '2001-10-30');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (9, 0, 'Egy zsak borso?', '2011-03-05');
INSERT INTO COMMENT (ID, VERSION, TEXT, TIMESTAMP) VALUES (10, 0, 'Az meg messze van...', '2016-04-25');

INSERT INTO WISHLIST (ID, VERSION, TITLE) VALUES (1, 0, 'Amit szeretnek karacsonyra');
INSERT INTO WISHLIST (ID, VERSION, TITLE) VALUES (2, 0, 'Lopjatok nekem');
INSERT INTO WISHLIST (ID, VERSION, TITLE) VALUES (3, 0, 'Kincskereso kincskodmon');
INSERT INTO WISHLIST (ID, VERSION, TITLE) VALUES (4, 0, 'Szokik a malna');
INSERT INTO WISHLIST (ID, VERSION, TITLE) VALUES (5, 0, 'Amit nem hozott el a mikulas');
INSERT INTO WISHLIST (ID, VERSION, TITLE) VALUES (6, 0, 'Tolem loptak el ezeket');
